version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
      # to prevent data loss when the container stops or is removed
      # must use a Docker volume to persist the database files.
volumes:
  sqlserver_data:
